fix: Fixes error TS9005 for Checkbox component
Fixes error reported on Slack:

```
Running `npm run build --workspaces --if-present` from the root gives me:

> @eyeo/ext-ui-components@0.0.1 build
> vite build && npx tsc

vite v5.4.6 building for production...
✓ 27 modules transformed.
dist/index.js  9.66 kB │ gzip: 3.50 kB
✓ built in 93ms
components/Checkbox.jsx:1:1 - error TS9005: Declaration emit for this file requires using private name 'Checkbox'. An explicit type annotation may unblock declaration emit.

1 import PropTypes from 'prop-types';
  ~~~~~~

Found 1 error in components/Checkbox.jsx:

```

## Description

Removes `@constructor` declaration in JSDoc.

## Checklist:
- [ ] ~~I have updated the release notes~~ I do not believe this is needed as this is an internal build fix.

---

- [ ] My changes require a documentation update and I have updated the documentation accordingly
      <br>_\- or -_
- [x] My changes didn't require a documentation update

---

- [ ] I have added tests to cover my changes
      <br>_\- or -_
- [x] My changes didn't require new tests

---

- [x] All new and existing tests passed

See eyeo/extensions/extensions!137