fix: Peer dependencies install incompatible npm packages in monorepo root [noissue]
## Description

This MR contains the following changes:
- Fixed: Added typescript dependency to monorepo root to fix the ESLint error.
- Fixed: Pinned ESLint version in ui-components, so that npm doesn't auto-upgrade to 9.10.0, which appears to be incompatible with 9.8.0.

This MR also contains the following unrelated changes:
- Added other peer dependencies (i.e. eslint, prettier) to monorepo root, in the hope to prevent further errors, and to clarify which versions the configuration files in the core/configs/ directory are written for.

## Motivation and Context

Running `npm run lint` currently results in two errors:

1. ESLint cannot find plugin
```
 ✖  @eyeo/ext-ui-components:lint
    > @eyeo/ext-ui-components@0.0.1 lint
    > eslint .
    
    
    Oops! Something went wrong! :(
    
    ESLint: 9.10.0
    
    Error: Cannot find module '@eslint/plugin-kit'
    Require stack:
    - ~/ui-components/node_modules/eslint/lib/languages/js/source-code/source-code.js
    - ~/ui-components/node_modules/eslint/lib/languages/js/source-code/index.js
    - ~/ui-components/node_modules/eslint/lib/linter/linter.js
    - ~/ui-components/node_modules/eslint/lib/linter/index.js
    - ~/ui-components/node_modules/eslint/lib/eslint/eslint.js
    - ~/ui-components/node_modules/eslint/lib/eslint/index.js
    - ~/ui-components/node_modules/eslint/lib/cli.js
    - ~/ui-components/node_modules/eslint/bin/eslint.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
        at Module._load (node:internal/modules/cjs/loader:922:27)
        at Module.require (node:internal/modules/cjs/loader:1143:19)
        at require (node:internal/modules/cjs/helpers:121:18)
        at Object.<anonymous> (~/ui-components/node_modules/eslint/lib/languages/js/source-code/source-code.js:23:62)
        at Module._compile (node:internal/modules/cjs/loader:1256:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
        at Module.load (node:internal/modules/cjs/loader:1119:32)
        at Module._load (node:internal/modules/cjs/loader:960:12)
        at Module.require (node:internal/modules/cjs/loader:1143:19)
    npm ERR! Lifecycle script `lint` failed with error: 
    npm ERR! Error: command failed 
    npm ERR!   in workspace: @eyeo/ext-ui-components@0.0.1 
    npm ERR!   at location: ~/ui-components 
```

2. ESLint uses incorrect TypeScript version
```
 ✖  adblockplus:lint
    > lint
    > npm run $ lint
    
    
    > $
    > npm-dollar lint
    
    Checking formatting...
    All matched files use Prettier code style!
    
    ~/host/adblockplus/src/bypass/background/bypass.ts
      202:68  error  Unsafe argument of type `any` assigned to a parameter of type `number`        @typescript-eslint/no-unsafe-argument
      244:28  error  Unsafe argument of type `any` assigned to a parameter of type `string | URL`  @typescript-eslint/no-unsafe-argument
    
    ~/host/adblockplus/src/core/messaging/background/messaging.ts
      165:18  error  Unsafe argument of type `any` assigned to a parameter of type `string | URL`                                              @typescript-eslint/no-unsafe-argument
      189:26  error  Unsafe argument of type `browser.Runtime.MessageSender` assigned to a parameter of type `BrowserMessageSenderWithOrigin`  @typescript-eslint/no-unsafe-argument
      217:43  error  Unsafe argument of type `browser.Runtime.MessageSender` assigned to a parameter of type `BrowserMessageSenderWithOrigin`  @typescript-eslint/no-unsafe-argument
    
    ~/host/adblockplus/src/core/messaging/background/serializable.ts
      49:46  error  Unsafe argument of type `any` assigned to a parameter of type `string`  @typescript-eslint/no-unsafe-argument
      60:46  error  Unsafe argument of type `any` assigned to a parameter of type `string`  @typescript-eslint/no-unsafe-argument
    
    ~/host/adblockplus/src/onpage-dialog/background/tab-manager.ts
      135:28  error  Unsafe argument of type `any` assigned to a parameter of type `number`  @typescript-eslint/no-unsafe-argument
      152:44  error  Unsafe argument of type `any` assigned to a parameter of type `number`  @typescript-eslint/no-unsafe-argument
      157:21  error  Unsafe argument of type `any` assigned to a parameter of type `number`  @typescript-eslint/no-unsafe-argument
      175:44  error  Unsafe argument of type `any` assigned to a parameter of type `number`  @typescript-eslint/no-unsafe-argument
      187:21  error  Unsafe argument of type `any` assigned to a parameter of type `number`  @typescript-eslint/no-unsafe-argument
      231:44  error  Unsafe argument of type `any` assigned to a parameter of type `number`  @typescript-eslint/no-unsafe-argument
      256:44  error  Unsafe argument of type `any` assigned to a parameter of type `number`  @typescript-eslint/no-unsafe-argument
      269:21  error  Unsafe argument of type `any` assigned to a parameter of type `number`  @typescript-eslint/no-unsafe-argument
    
    ~/host/adblockplus/src/unload-cleanup/background/unload-cleanup.ts
      61:32  error  Unsafe argument of type `any` assigned to a parameter of type `number | undefined`  @typescript-eslint/no-unsafe-argument
    
    ~/host/adblockplus/src/yt-wall-detection/background/detection.ts
      69:14  error  Unsafe argument of type `any` assigned to a parameter of type `number`                         @typescript-eslint/no-unsafe-argument
      69:29  error  Unsafe argument of type `browser.Runtime.MessageSender` assigned to a parameter of type `Tab`  @typescript-eslint/no-unsafe-argument
    
    ✖ 18 problems (18 errors, 0 warnings)
    
    npm ERR! Lifecycle script `$` failed with error: 
    npm ERR! Error: command failed 
    npm ERR!   in workspace: adblockplus 
    npm ERR!   at location: ~/host/adblockplus 
    npm ERR! Lifecycle script `lint` failed with error: 
    npm ERR! Error: command failed 
    npm ERR!   in workspace: adblockplus 
    npm ERR!   at location: ~/host/adblockplus 
```

as well as the following, when run via `npm run -w host/adblockplus $ lint.js`:

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.3.0

YOUR TYPESCRIPT VERSION: 5.6.3

Please only submit bug reports when using the officially supported version.

=============
```

This appears to be due to peer dependencies falling back on whatever version of the npm package that is installed in the monorepo root, rather than the version that is specified in the respective workspace.

Note that this change may not sufficiently address the problem, and should therefore only be seen as a quickfix. Ideally, we could force peer dependencies to use the version defined in the workspace instead of the one in the monorepo root. So if we could (a) somehow prevent certain npm packages to be installed in the monorepo root, or (b) give priority to the version in the workspace, those could be more reliable solutions.

## Checklist:

- [x] My changes didn't require a documentation update
- [x] My changes didn't require new tests
- [x] All new and existing tests passed

See eyeo/extensions/extensions!227