test: Retry temporary premium activation flow (AB) [noissue]
## Description

Retries the temporary premium activation flow (AB)

## Motivation and Context

Occasionally the temporary premium activation fails because the element `#premium_status_msg` is not found: https://gitlab.com/eyeo/extensions/extensions/-/jobs/8540414248

I was able to reproduce the issue locally after calling `enableTemporaryPremium` multiple times on new browser instances.

The first approach was to refresh the options premium page when the element wasn't located, but that didn't help:

```
Extension: AdBlock 6.11.0 MV3
    Upgrade Extension
Element "#premium_status_msg" is not displayed, refreshing the page and retrying...
      1) temporary


  0 passing (37s)
  1 failing

  1) AdBlock upgrade end-to-end tests
       Upgrade Extension
         temporary:
     TimeoutError: Element "#premium_status_msg" was not displayed after 4000ms
Wait timed out after 4086ms
```

The second approach I tried seems to fix the issue. That is retrying the whole activation flow inside a `driver.wait` function.

## Checklist:

- [X] My changes didn't require a documentation update
- [X] My changes didn't require new tests
- [X] All new and existing tests passed

See eyeo/extensions/extensions!313