fix: Add retry logic to the sending of telemetry data [EXT-107]
This MR includes the following changes:

- added a backup ping server URL.
- added logic to send ping data to the back ping server when the initial ping fails (two immediate attempts will be made).
- updated the `cache` property on fetch request to 'no-store' so the browser fetches the resource from the remote server without first looking in the cache, and will not update the cache with the downloaded resource.
- updated the hard-coded backup log server IP address to the correct server name to avoid CORS issues when using an IP address in a fetch request.
- added additional debug information to the error log message requests sent to the backup log server


## Testing hints

Testing error scenarios can be complex, especially with network and remote server errors.

The following steps can recreate a failure to the ping server that will invoke the new ping retry logic.

1. Fresh install AdBlock with these changes

2. On the Console tab of the Service Worker, run the following:
- `Prefs.set('ping_server_url', "https://bad-one.getadblock.com/");`
- `TELEMETRY.pingNow()`

This will update the primary ping server URL to an invalid URL and force a ping request.

3. The extension should then retry the ping to the new backup server (which should succeed) and send a log message to the log server.
After running the two code snippets in step 2, you should see the following on the back console:
```
network error during ping
ping server URL: https://bad-one.getadblock.com/
error:  TypeError: Failed to fetch
    at postData (fetch-util.js:22:1)
    at telemetry-ping.js:93:38
    at new Promise (<anonymous>)
    at Telemetry.sendPingData (telemetry-ping.js:88:1)
    at Telemetry.pingNow (telemetry-ping.js:143:1)
no response from ping
```

On the Network tab of the Service Worker, you should see the following:
1. a failed network request to "https://bad-one.getadblock.com/"
2. a successful network request to "https://ping-retry.getadblock.com/stats/"
3. a successful network request to "https://logbackup.getadblock.com/v2/record_log.php" with a 'fetch_error' payload with the additional debug data in the payload

See eyeo/extensions/extensions!62